version: '3'

services:
  web:
    build: .
    image: protetor-de-pdf:latest  # Define a imagem do seu projeto Flask
    ports:
      - "5000:5000"  # Mapeia a porta 5000 do container para a porta 5000 da máquina local
    environment:
      - FLASK_ENV=development  # Define o ambiente como desenvolvimento (pode ser "production")
    networks:
      - pdf-network

  # Caso queira usar um banco de dados, por exemplo PostgreSQL:
  # db:
  #   image: postgres
  #   environment:
  #     POSTGRES_PASSWORD: "postgres"  # Senha do banco
  #   ports:
  #     - "5432:5432"  # Mapeia a porta do banco de dados
  #   networks:
  #     - pdf-network

networks:
  pdf-network:
    driver: bridge
